{
 "title": "Locust Swarmadmin",
 "time": { "from": "2021-10-14T11:35:55.737Z", "to": "2021-10-14T11:46:43.737Z" },
 "templating": {
  "list": [
   { "name": "locust_instance", "label": "Instance", "query": "locust_avg_content_length" }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(locust_instances_total)" }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(locust_instances_running)" }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(locust_workers)" }
   ]
  },
  { "title": "Instance $locust_instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "locust_instance" },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(locust_user_count{locust_instance=\"$locust_instance\"})"
    }
   ]
  },
  {
   "title": "Fail Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(locust_fail_ratio{locust_instance=\"$locust_instance\"})*100"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (method) (rate(locust_num_requests{locust_instance=\"$locust_instance\"}[10s]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(locust_current_rps{locust_instance=\"$locust_instance\"})",
     "legendFormat": "Requests per Second"
    },
    {
     "expr": "0.0 - sum(locust_current_fail_per_sec{locust_instance=\"$locust_instance\"})",
     "legendFormat": "Fails per Second"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(locust_current_rps{locust_instance=\"$locust_instance\"})"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_avg_response_time{locust_instance=\"$locust_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(locust_num_requests{locust_instance=\"$locust_instance\"}[10s]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Worker CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_cpu_usage{locust_instance=\"$locust_instance\"}",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  {
   "title": "Worker User Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_user_count{locust_instance=\"$locust_instance\"}",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (method, name, locust_instance) (rate(locust_num_requests[10s]))"
    }
   ]
  }
 ]
}